import { createServiceDefinition } from '../service-factory';
import type { ServiceDefinition } from '../types';

const service = createServiceDefinition({
  copyFamily: 'image-generation',
  key: 'llm402-gpt-5-image-generation',
  providerKey: 'llm402',
  name: 'GPT-5-image generation',
  endpointUrl: 'https://llm402.ai/v1/images/generations',
  resultLabel: 'Generate detailed, user-facing images on demand',
  category: 'Image generation',
  supportStatus: 'supported',
  lastCheckedAt: '2026-04-19',
  priceLabel: '105 sats (~$0.03)',
  exampleOutput: {
    kind: 'image',
    title: 'Example output',
    caption:
      'Actual image from the blog post comparison, showing the higher-detail GPT-5-image output for the same vending-machine prompt.',
    imageSrc: `${import.meta.env.BASE_URL}services/llm402-gpt-5-image-generation/blog.png`,
    imageAlt: 'A detailed pixel art AI-ART DISPENSER vending machine with Insert Coin and Generate buttons, various pixel art thumbnails in the slots and lightning bolt coins scattered at the base, generated by GPT-5-image',
    details: ['Provider: llm402.ai', 'Service: GPT-5-image generation', 'Endpoint: /v1/images/generations', 'Cost: 105 sats (~$0.03)'],
  },
  examplePrompt:
    'Use llm402.ai to generate an image with model openai/gpt-5-image and prompt: A vending machine dispensing AI-generated artwork for lightning bolt coins, each slot showing a different image style, pixel art.',
  variantTitle: ({ agentName, providerName, serviceName }) => `Generate detailed images with ${agentName} using ${providerName} ${serviceName}`,
  variantDescription: ({ agentName, providerName, serviceName }) =>
    `Enable ${agentName} to generate higher-detail images through ${providerName} ${serviceName} for 105 sats, with no account, no API key, no prepaid balance, and no human needed.`,
  heroSummary: ({ agentName, providerName, serviceName }) =>
    `Give ${agentName} access to ${providerName}'s ${serviceName} endpoint when the output needs to be polished enough for user-facing pages, richer mockups, and more detailed visual work.`,
  heroBulletHighlights: () => [
    'Better fit when the image will end up in front of a user instead of staying a rough internal draft.',
    'Uses the same endpoint and payment flow as the cheaper llm402.ai image tiers, just with a higher-quality model.',
  ],
  whyItWorks: ({ agentName, providerName }) => [
    `${agentName} can choose a higher-quality image path without changing the integration or asking a human to manage another AI account.`,
    `${providerName} keeps the request flow identical across models, so the agent can trade more sats for better image quality when it matters.`,
    'This is the stronger option for polished launch assets, hero graphics, and visuals that need to look coherent on first view.',
  ],
  useCases: () => [
    'Generate polished hero images for landing pages or product launches',
    'Create higher-quality campaign visuals and social graphics',
    'Produce detailed mockups when rough draft quality is not enough',
  ],
  faqResultDescription: ({ providerName, serviceName }) =>
    `${providerName} ${serviceName} returns more detailed, coherent generated images from the same synchronous image endpoint, making it a better fit for polished user-facing visuals than the faster draft tier.`,
}) satisfies ServiceDefinition;

export default service;
