import { createServiceDefinition } from '../service-factory';
import { buildCostDetail, createSatsFixedPrice } from '../pricing';
import type { ServiceDefinition } from '../types';

const pricing = createSatsFixedPrice(21, 'per image');

const service = createServiceDefinition({
  copyFamily: 'image-generation',
  key: 'llm402-flux-1-schnell-image-generation',
  providerKey: 'llm402',
  name: 'FLUX.1-schnell image generation',
  endpointUrl: 'https://llm402.ai/v1/images/generations',
  resultLabel: 'Generate images on demand for real-time agent workflows',
  category: 'Image generation',
  supportStatus: 'supported',
  lastCheckedAt: '2026-04-19',
  pricing,
  exampleOutput: {
    kind: 'image',
    title: 'Example output',
    caption:
      'Actual image from the blog post comparison, showing the fast FLUX.1-schnell output for the vending-machine prompt.',
    imageSrc: `${import.meta.env.BASE_URL}services/llm402-flux-1-schnell-image-generation/blog.jpg`,
    imageAlt: 'A pixel art vending machine with lightning bolt coin slots, each slot displaying a different style of AI-generated artwork, generated by FLUX.1-schnell',
    details: ['Provider: llm402.ai', 'Service: FLUX.1-schnell image generation', 'Endpoint: /v1/images/generations', buildCostDetail(pricing)],
  },
  examplePrompt:
    'Generate a pixel-art vending machine dispensing AI-generated artwork for lightning bolt coins, with each slot showing a different image style, using llm402.ai with the Alby payments skill.',
  variantTitle: ({ agentName, providerName, serviceName }) => `Generate images with ${agentName} using ${providerName} ${serviceName}`,
  variantDescription: ({ agentName, providerName, serviceName, priceLabel }) =>
    `Enable ${agentName} to generate images through ${providerName} ${serviceName} for ${priceLabel}, with no account, no API key, no prepaid balance, and no human needed.`,
  heroSummary: ({ agentName, providerName, serviceName }) =>
    `Give ${agentName} direct access to ${providerName}'s ${serviceName} endpoint so it can turn prompts into images in one paid request instead of stopping for account setup, credits, or manual checkout.`,
  heroBulletHighlights: () => [
    'Fast enough for real-time thumbnail, mockup, and draft-image workflows.',
    'Uses the standard OpenAI-style images endpoint so the integration path is simple.',
  ],
  whyItWorks: ({ agentName, providerName, priceLabel }) => [
    `${agentName} can generate an image exactly when it needs one instead of kicking the task back to a human for another AI account.`,
    `${providerName} prices the fastest tier at ${priceLabel}, which makes one-off visual requests easy to justify inside bigger workflows.`,
    'The payment, retry, and authorization flow is handled automatically by the Alby payments skill.',
  ],
  useCases: () => [
    'Generate social images and blog thumbnails from a text brief',
    'Create quick visual drafts for landing pages, docs, or product concepts',
    'Produce on-demand illustrations inside a larger autonomous workflow',
  ],
  faqResultDescription: ({ providerName, serviceName }) =>
    `${providerName} ${serviceName} returns generated images from a synchronous API call, so agents can create drafts, thumbnails, and visual assets without waiting on a separate download or polling workflow.`,
}) satisfies ServiceDefinition;

export default service;
